image: continuumio/miniconda3:latest

stages:
  - build
  - codechecks
  - tests

# global/ default before_script can be overriden
before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - apt-get update -y
  - apt-get install gcc -y
  - conda create --name pqueens -y python=3.7
  - source activate pqueens
  - pip install -r requirements.txt

codechecks:
  stage: codechecks
  script:
    - pylint --output-format=parseable pqueens | tee track_pylint.txt
  artifacts:
    name: "$CI_JOB_NAME-$CI_JOB_ID"
    paths:
      - track_pylint.txt
    when: on_failure
    expire_in: 4 weeks

full_test_suite:
  stage: tests
  script:
  - python setup.py test

services:
  - name: mongo:3.4
    alias: mongodb
