image: continuumio/anaconda3


full_test_and_build_suite:
  script:
  - export PATH="/opt/conda/bin:$PATH"
  - conda update conda && conda update python
  - apt-get update -y
  - apt-get install gcc -y
  - conda create --name pqueens -y python=3.7.3
  - source activate pqueens
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install numpy
  - pip install -r requirements.txt
  - python setup.py test


services:
  - name: mongo:3.4
    alias: mongodb
