image: continuumio/anaconda3:4.4.0


full_test_and_build_suite:
  script:
  - apt-get update -y
  - apt-get install gcc -y
  - conda create --name pqueens -y
  - source activate pqueens
  - pip install -r requirements.txt
  # do normal unit testing
  # - python -m unittest discover -s pqueens/tests/
  # use coverage to gauge test coverage
  - coverage run -m unittest discover -s pqueens/tests
  # transfer test results to codecov.io
  - codecov --token=8eecedcc-6782-468a-b066-0e641741f210

#services:
#  - mongo:3.4
