stages:
  - codechecks
  - tests
  - pages

default:
  image: continuumio/miniconda3:latest

  services:
    - name: mongo:3.4
      alias: mongodb

  # global/ default before_script can be overriden
  before_script:
    - export PIP_CACHE_DIR="/opt/cache/pip"
    - apt-get update
    - apt-get install gcc -y
    - apt-get install libgl1-mesa-glx -y
    - apt-get install libxt6
    - conda env create -f environment.yml -n queens
    - source activate queens
    - python setup.py develop

codechecks:
  stage: codechecks
  script:
    - pylint -j 4 --output-format=parseable pqueens | tee track_pylint.txt
  artifacts:
    name: "$CI_JOB_NAME-$CI_JOB_ID"
    paths:
      - track_pylint.txt
    when: on_failure
    expire_in: 4 weeks
  tags:
    - queens-docker

full_test_suite_develop:
  stage: tests
  script:
  - pytest -n4
  except:
    refs:
      - master
  tags:
    - queens-docker

full_test_suite_master:
  stage: tests
  script:
    - pytest --cov-report=html:$CI_PROJECT_DIR/html_coverage_report
    - sphinx-apidoc -o doc/source pqueens -f -M
    - cd doc
    - apt-get install pandoc -y
    # "make html" triggers:
    - sphinx-build -b html -d build/doctrees   source build/html
  artifacts:
    name: coverage_report
    paths:
      - html_coverage_report
      - doc/build/html
    when: on_success
    expire_in: 3 days
  only:
    refs:
      - master
  tags:
    - queens-docker

pages:
  stage: pages
  # disable cache on this job since we do not need conda env here
  dependencies:
    - full_test_suite_master
  before_script:
    - pip install anybadge
    - mkdir public
  script:
    - mv html_coverage_report public/coverage_report
    - mv doc/build/html public/docs
    # Create sphinx badge
    - anybadge -l sphinx -v ok --color=green -f public/sphinx-badge.svg

  artifacts:
      # store the public path in artifact
      # this is needed since in a subsequent deploy stage (automatically generated by GitLab)
      # the content of the below artifact is published on GitLab Pages
      paths:
          - public
  only:
      refs:
          - master
  tags:
    - queens-docker

