image: continuumio/anaconda3


full_test_and_build_suite:
  script:
  - conda update conda && conda update python
  - apt-get update -y
  - apt-get install gcc -y
  - conda create --name pqueens -y python=3.6
  - source activate pqueens
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install numpy
  - pip install -r requirements.txt
  # do normal unit testing
  # - python -m unittest discover -s pqueens/tests/
  # use coverage to gauge test coverage
  #- coverage run -m unittest discover -s pqueens/tests
  - coverage run -m pytest pqueens/tests
  # transfer test results to codecov.io
  - codecov --token=8eecedcc-6782-468a-b066-0e641741f210

services:
  - name: mongo:3.4
    alias: mongodb
