repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/saygox/commitizen
    rev: 09fa312b7846850f44f7860632685189e37c1bec
    hooks:
    -   id: commitizen-prepare-commit-msg
        stages: [prepare-commit-msg]
    -   id: commitizen
        stages: [commit-msg]
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.3
    hooks:
    -   id: vulture
-   repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    -   id: docformatter
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        always_run: false
        pass_filenames: true
    -   id: isort
        name: isort (python)
        entry: isort
        language: system
        always_run: false
        pass_filenames: true
    -   id: black
        name: black
        entry: black
        language: python
        types: ["python"]
        always_run: false
        pass_filenames: true
