repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/myint/docformatter
    rev: v1.6.0.rc1
    hooks:
      - id: docformatter
        args: [--in-place]
  - repo: local
    hooks:
      - id: vulture
        name: vulture
        entry: vulture
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
        always_run: false
        pass_filenames: true
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
      - id: commitizen
        name: commitizen
        entry: cz
        args: ['check', '--commit-msg-file', '.git/COMMIT_EDITMSG']
        pass_filenames: false
        language: system
        stages: [commit-msg]
      - id: isort
        name: isort (python)
        entry: isort
        language: python
        always_run: false
        pass_filenames: true
        additional_dependencies: ["toml"]
      - id: black
        name: black
        entry: black
        language: python
        types: ["python"]
        always_run: false
        pass_filenames: true
        additional_dependencies: ["toml"]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
        always_run: false
        pass_filenames: true
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args:
          - > # This is needed to lint the jinja templates
            -d={extends: default, rules: {braces: {max-spaces-inside: 1}
            , brackets: disable, document-start: disable}}
          - -f=colored
