repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/saygox/commitizen
    rev: 09fa312b7846850f44f7860632685189e37c1bec
    hooks:
      - id: commitizen-prepare-commit-msg
        stages: [prepare-commit-msg]
        additional_dependencies: ["markupsafe==2.0.1"]
      - id: commitizen
        stages: [commit-msg]
        additional_dependencies: ["markupsafe==2.0.1"]
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
      - id: vulture
        additional_dependencies: ["toml"]
        always_run: false
        pass_filenames: true
  - repo: https://github.com/myint/docformatter
    rev: v1.6.0.rc1
    hooks:
      - id: docformatter
        args: [--in-place]
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: ["toml"]
  - repo: local
    hooks:
      - id: isort
        name: isort (python)
        entry: isort
        language: python
        always_run: false
        pass_filenames: true
        additional_dependencies: ["toml"]
      - id: black
        name: black
        entry: black
        language: python
        types: ["python"]
        always_run: false
        pass_filenames: true
        additional_dependencies: ["toml"]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
        always_run: false
        pass_filenames: true
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args:
          - > # This is needed to lint the jinja templates
            -d={extends: default, rules: {braces: {max-spaces-inside: 1}
            , brackets: disable, document-start: disable}}
          - -f=colored
