repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
      - id: end-of-file-fixer
        name: fix end of files
        entry: end-of-file-fixer
        language: python
        types: [text]
      - id: check-added-large-files
        name: check for added large files
        entry: check-added-large-files
        language: python
        types: [text]
      - id: vulture
        name: vulture
        entry: vulture
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
        always_run: false
        pass_filenames: true
      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
      - id: docformatter
        name: docformatter
        entry: docformatter
        args: [--in-place]
        language: python
        types: ["python"]
      - id: commitizen
        name: commitizen
        entry: cz
        args: ['check', '--commit-msg-file', '.git/COMMIT_EDITMSG']
        pass_filenames: false
        language: system
        stages: [commit-msg]
      - id: isort
        name: isort (python)
        entry: isort
        language: python
        always_run: false
        pass_filenames: true
        additional_dependencies: ["toml"]
      - id: black
        name: black
        entry: black
        language: python
        types: ["python"]
        always_run: false
        pass_filenames: true
        additional_dependencies: ["toml"]
      - id: yamllint
        name: yamllint
        entry: yamllint
        args:
          - > # This is needed to lint the jinja templates
            -d={extends: default, rules: {braces: {max-spaces-inside: 1}
            , brackets: disable, document-start: disable}}
          - -f=colored
        language: python
        types: ["yaml"]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
        always_run: false
        pass_filenames: true
