name: queens 
channels:
  - defaults
  - conda-forge
dependencies:
###### use requirements without version fixed specifier where possible ######
  - python==3.7
  - cython
  - numpy>=1.16.2
  - scipy>=1.2.1
  - scikit-learn
  - arviz
  - pandas
  - xarray
# for database interfacing
  - pymongo
# for design of experiments
  - pyDOE
# for Gaussian Processes
  - gpy
# for documentation
  - sphinx
  - nbsphinx
  - jupyter
# making fancy plots
  - matplotlib
  - seaborn
  - plotly
# testing framework
  - pytest>=3.0.0
  - pytest-codestyle
  - pytest-cov
  - pytest-mock
# for running tests in parallel
  - pytest-xdist
# create mock objects for unit testing
  - mock
# linting, check code  -style (PEP8)
  - astroid>=2.5.1
  - pylint>=2.5.1
  - isort<5
# make ascii  -art printsc
  - pyfiglet
# code formatter
  - black
# a smart progress meter for loops
  - tqdm
# visualization toolkit that can manage mesh data
  - vtk
# enforce package compliance of parso package
  - parso>=0.8.0
# wrapper around numpy for automated differentiation
  - autograd
# multiprocessing with more complex python objects
  - pathos
# it's recommended to list pip explicitly
  - pip
  - pip:
# for sensitivity analysis
    - SALib>=1.3.3
    - docker
# Pythonic interface to ANSYS binary files
    - pyansys
# for space filling subsets
    - diversipy
# electrochemical impedance spectroscopy (EIS)
    - impedance
# Utility to handle pylint exit codes scripting friendly
    - pylint-exit
# Tool to perform license checks
    - liccheck
# gpflow to build tensorflow based (latent) variable Gaussian Processes and variational GPs
    - gpflow
# tensorflow and tensorflow probability
    - tensorflow
    - tensorflow-probability
# for Quasi-Monte-Carlo methods
    - torch
