name: queens
channels:
  - defaults
  - conda-forge
dependencies:
###### use requirements without version fixed specifier where possible ######
  - python==3.8
  - cython==0.29.26
  - numpy==1.21.2
  - scipy==1.7.3
  - numba==0.53.1
  - scikit-learn==1.0.1
  - pandas==1.2.4
  - pip
<<<<<<< HEAD
  - pip:
    - numpy
    - pandas
# for sensitivity analysis
    - SALib>=1.3.3
    - docker
# Pythonic interface to ANSYS binary files
    - pyansys
# for space filling subsets
    - diversipy
# electrochemical impedance spectroscopy (EIS)
    - impedance
# Utility to handle pylint exit codes scripting friendly
    - pylint-exit
# Tool to perform license checks
    - liccheck
# gpflow to build tensorflow based (latent) variable Gaussian Processes and variational GPs
    - gpflow
# tensorflow and tensorflow probability
    - tensorflow
    - tensorflow-probability
# for Quasi-Monte-Carlo methods
    - torch
# for Chopin SMC
    - particles
=======
  - gpy==1.10.0
>>>>>>> master
